// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBse9XiXFVnXkC20Bld-6y7tOWm7iJffJQ',
    appId: '1:952115720746:web:d6da6ed220f1e9f63a4953',
    messagingSenderId: '952115720746',
    projectId: 'readtrack-63aef',
    authDomain: 'readtrack-63aef.firebaseapp.com',
    storageBucket: 'readtrack-63aef.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ZIn_XFlRLFr8eOecqhls5gDlRTzkEsM',
    appId: '1:952115720746:ios:9846431903b19a003a4953',
    messagingSenderId: '952115720746',
    projectId: 'readtrack-63aef',
    storageBucket: 'readtrack-63aef.firebasestorage.app',
    iosClientId: '952115720746-199c73nf9rp7m67v0bgnjtgrahvok93h.apps.googleusercontent.com',
    iosBundleId: 'com.example.readTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBse9XiXFVnXkC20Bld-6y7tOWm7iJffJQ',
    appId: '1:952115720746:web:758b651219a54f8e3a4953',
    messagingSenderId: '952115720746',
    projectId: 'readtrack-63aef',
    authDomain: 'readtrack-63aef.firebaseapp.com',
    storageBucket: 'readtrack-63aef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ZIn_XFlRLFr8eOecqhls5gDlRTzkEsM',
    appId: '1:952115720746:ios:9846431903b19a003a4953',
    messagingSenderId: '952115720746',
    projectId: 'readtrack-63aef',
    storageBucket: 'readtrack-63aef.firebasestorage.app',
    iosClientId: '952115720746-199c73nf9rp7m67v0bgnjtgrahvok93h.apps.googleusercontent.com',
    iosBundleId: 'com.example.readTrack',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0QXuzovCG6z3Oq_iwgqrL2dDtysf9Zxw',
    appId: '1:952115720746:android:efc60b1308e831053a4953',
    messagingSenderId: '952115720746',
    projectId: 'readtrack-63aef',
    storageBucket: 'readtrack-63aef.firebasestorage.app',
  );

}